a = int(input("Enter the value of a: "))
b = int(input("Enter the value of b: "))
print("Arithmetic Operators of a and b are:")
print("Addition: ", a + b)
print("Subtraction: ", a - b)
print("Multiplication: ", a * b)
print("Division: ", a/b)
print("Modulus: ", a % b)
print("Floor Division: ",a // b)
print("Exponentiation: ", a**b)